posts = [
    {
        'title': 'ChatGPT: Un genio de las letras, un aprendiz en números',
        'body': '<p>Cuáles son las limitaciones de ChatGPT en la resolución de problemas matemáticos? A pesar de ser un modelo avanzado de lenguaje, ChatGPT enfrenta desafíos significativos al abordar cálculos y problemas matemáticos complejos.</p><p>Una de las razones principales de estas dificultades es que el modelo no está diseñado para realizar cálculos aritméticos precisos. En lugar de eso, genera respuestas basadas en patrones aprendidos a partir de datos textuales. Esto significa que, aunque puede ofrecer explicaciones sobre conceptos matemáticos, a menudo comete errores en cálculos directos o en la resolución de ecuaciones.</p><p>El artículo también menciona que, a diferencia de los sistemas diseñados específicamente para matemáticas, como Wolfram Alpha, ChatGPT carece de una comprensión profunda de las reglas matemáticas. En su lugar, utiliza un enfoque probabilístico para generar texto, lo que puede llevar a respuestas incorrectas, especialmente cuando se trata de operaciones que requieren precisión.</p><p>Además, se discute el impacto del entrenamiento del modelo en su rendimiento. ChatGPT ha sido entrenado con una gran cantidad de datos textuales, pero esto no incluye suficientes ejemplos específicos de problemas matemáticos. Como resultado, su capacidad para manejar problemas numéricos es limitada.</p><p>Por último, el artículo sugiere que futuras versiones del modelo podrían mejorar en este aspecto si se integran componentes especializados para el cálculo y la resolución matemática. Sin embargo, por ahora, los usuarios deben ser cautelosos al confiar en ChatGPT para tareas matemáticas complejas y considerar utilizar herramientas diseñadas específicamente para esos fines.</p>',
        'thumbnail': '/assets/article_images/1.jpg',
        'source': 'https://techcrunch.com/2024/10/02/why-is-chatgpt-so-bad-at-math/',
        'date': '2 de octubre de 2024',
    },
    {
        'title': 'The Avengers movie was so cool!',
        'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum sol',
        'thumbnail': '/assets/images/thumbnail_resized.png',
        'source': 'https://techcrunch.com/2024/10/01/palmer-luckey-tried-to-crush-aeronautics-startup-salient-motion-but-anduril-backer-a16z-invested/'
    },
    {
        'title': 'This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.',
        'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum sol',
        'thumbnail': '/assets/images/thumbnail_resized.png',
        'source': 'https://techcrunch.com/2024/10/01/palmer-luckey-tried-to-crush-aeronautics-startup-salient-motion-but-anduril-backer-a16z-invested/'
    },
    {
        'title': 'Instagram Implementa Restricciones para Proteger a Adolescentes en la Plataforma',
        'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum sol',
        'thumbnail': '/assets/images/thumbnail_resized.png',
        'source': 'https://techcrunch.com/2024/10/01/palmer-luckey-tried-to-crush-aeronautics-startup-salient-motion-but-anduril-backer-a16z-invested/'
    },
    {
        'title': 'Apple lanza el Watch Series 10 con detección de apnea de sueño y profundidad de agua, y el iPhone 16 se lanza sin su funcionalidad más esperada de IA',
        'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum sol',
        'thumbnail': '/assets/images/thumbnail_resized.png',
        'source': 'https://techcrunch.com/2024/10/01/palmer-luckey-tried-to-crush-aeronautics-startup-salient-motion-but-anduril-backer-a16z-invested/'
    }
]
