"""Remove views column from Article table

Revision ID: 18a6db12f85b
Revises: 14da7ae3c55e
Create Date: 2024-10-04 15:47:43.864804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a6db12f85b'
down_revision = '14da7ae3c55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
