"""Add views column to Article

Revision ID: be46dac141cd
Revises: a9de077ca1eb
Create Date: 2024-10-07 12:16:40.822976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be46dac141cd'
down_revision = 'a9de077ca1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
       

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
